spring.profiles.active: h2
spring.profiles.include: enable-hystrix, enable-cors, enable-feign

---

# 默认
server.port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.Oracle10gDialect
    show_sql: true
    format_sql: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.threadpool.default:
  coreSize: 200
  maxQueueSize: 300
  queueSizeRejectionThreshold: 20
feign.hystrix.enabled: true
marathon-lb-internal.ribbon.listOfServers: marathon-lb-internal.marathon.mesos
custom:
  baseurl: @baseurl@
  title: @name@
  description: @description@
  version: @version@

---

# 开发环境
spring:
  profiles: dev
  datasource:

---

# 测试环境
spring:
  profiles: test
  datasource:


---

# 生产环境
spring:
  profiles: prod
  datasource:

---

# 内嵌H2
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS UCR_CEN1
    username: sa
  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  jpa.hibernate.ddl-auto: create-drop
spring.h2.console.enabled: true